### ISSUE TITLE
Leap.Hand.SphereCenter does not work after Leap.Hand.TransformedCopy

### ISSUE THREAD

**Issue by cherullo** [leapmotion-examples/UnityModules#7]
The code inside calculateSphere() does not account for the scaling suffered in TransformedCopy when calculating the _sphereRadius (since _maxSphereradius and _minSphereRadius are always in millimeters), and then _sphereCenter is wrong too.

**Comment by jo3w4rd** [comment]
Thanks for reporting this. Hand.SphereCenter and Sphere radius are being removed in the next drop, so this issue is moot. Closing.
